import type { Project, ProjectEvent, UserRecord } from "./types";

/** Demo projects so the app is usable without a live DOB sync. */
export const SEED_PROJECTS: Project[] = [
  {
    id: "nyc:1001234:B00123456-I1",
    city: "nyc",
    bin: "1001234",
    jobNumber: "B00123456-I1",
    address: "350 5th Avenue",
    borough: "Manhattan",
    zip: "10118",
    latitude: 40.7484,
    longitude: -73.9857,
    jobType: "Alteration",
    buildingType: "Commercial",
    occupancy: "Commercial",
    description: "Interior renovation and lobby fit-out for retail conversion",
    estimatedJobCost: 4_200_000,
    phase: "interior_finishing",
    phaseConfidence: 0.84,
    score: 96,
    scoreReasons: [
      "Interior + MEP activity — peak signage buying window",
      "Phase fit: interior finishing",
      "Permit activity in the last 7 days",
      "Substantial job cost ($2M+)",
      "Commercial / retail / mixed-use classification",
      "GC identified: Apex Construction LLC",
      "No competing sign permit detected",
    ],
    estValueLow: 15000,
    estValueHigh: 25000,
    buyingWindowEstimate: "2–4 weeks",
    gcName: "Apex Construction LLC",
    architectName: "Harbor + Lane Architects",
    ownerName: "Empire Realty Group",
    hasSignPermit: false,
    lastActivityAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    filingDate: new Date(Date.now() - 40 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "nyc:1005678:B00987654-I1",
    city: "nyc",
    bin: "1005678",
    jobNumber: "B00987654-I1",
    address: "200 West 57th Street",
    borough: "Manhattan",
    zip: "10019",
    latitude: 40.7655,
    longitude: -73.9808,
    jobType: "New Building",
    buildingType: "Mixed Use",
    occupancy: "Mixed Use",
    description: "New mixed-use tower nearing CO",
    estimatedJobCost: 85_000_000,
    phase: "sign_ready",
    phaseConfidence: 0.88,
    score: 91,
    scoreReasons: [
      "Certificate of Occupancy activity — near completion",
      "Large project ($10M+) — earlier / bigger signage budgets",
      "GC identified: Skyline Builders",
      "No competing sign permit detected",
    ],
    estValueLow: 45000,
    estValueHigh: 80000,
    buyingWindowEstimate: "1–3 weeks",
    gcName: "Skyline Builders",
    architectName: "Northform Studio",
    ownerName: "57th Street Partners",
    hasSignPermit: false,
    lastActivityAt: new Date(Date.now() - 9 * 86400000).toISOString(),
    filingDate: new Date(Date.now() - 400 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "nyc:3001122:B00444555-I1",
    city: "nyc",
    bin: "3001122",
    jobNumber: "B00444555-I1",
    address: "88 Wythe Avenue",
    borough: "Brooklyn",
    zip: "11249",
    latitude: 40.7215,
    longitude: -73.958,
    jobType: "Alteration CO",
    buildingType: "Commercial",
    occupancy: "Restaurant",
    description: "Restaurant build-out with MEP rough-in",
    estimatedJobCost: 1_100_000,
    phase: "mep",
    phaseConfidence: 0.76,
    score: 74,
    scoreReasons: [
      "MEP work types active (PL / MH / EL / FA)",
      "Activity within 30 days",
      "Commercial / retail / mixed-use classification",
    ],
    estValueLow: 8000,
    estValueHigh: 16000,
    buyingWindowEstimate: "4–8 weeks",
    gcName: "Borough Fitout Co",
    architectName: null,
    ownerName: "Wythe Hospitality",
    hasSignPermit: false,
    lastActivityAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    filingDate: new Date(Date.now() - 70 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "nyc:4002233:B00777888-I1",
    city: "nyc",
    bin: "4002233",
    jobNumber: "B00777888-I1",
    address: "31-00 47th Avenue",
    borough: "Queens",
    zip: "11101",
    latitude: 40.7428,
    longitude: -73.9352,
    jobType: "New Building",
    buildingType: "Commercial",
    occupancy: "Commercial",
    description: "Foundation and structural steel for warehouse conversion",
    estimatedJobCost: 12_500_000,
    phase: "foundation_structure",
    phaseConfidence: 0.7,
    score: 58,
    scoreReasons: [
      "Foundation / structure or new building signals",
      "Large project ($10M+) — earlier / bigger signage budgets",
      "Buy-early flag for large commercial sites",
    ],
    estValueLow: 20000,
    estValueHigh: 40000,
    buyingWindowEstimate: "6–12 weeks",
    gcName: "LIC Structures Inc",
    architectName: "Gridline Architects",
    ownerName: "47th Ave Holdings",
    hasSignPermit: false,
    lastActivityAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    filingDate: new Date(Date.now() - 25 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "nyc:1009988:B00111222-I1",
    city: "nyc",
    bin: "1009988",
    jobNumber: "B00111222-I1",
    address: "9 East 53rd Street",
    borough: "Manhattan",
    zip: "10022",
    latitude: 40.7596,
    longitude: -73.9748,
    jobType: "Alteration",
    buildingType: "Commercial",
    occupancy: "Retail",
    description: "Retail renovation — sign permit already filed",
    estimatedJobCost: 900_000,
    phase: "signage_filed",
    phaseConfidence: 0.9,
    score: 52,
    scoreReasons: [
      "Sign permit (SG) detected at this BIN",
      "Sign permit already filed — lower new-opportunity score; check uncovered scope",
      "Commercial / retail / mixed-use classification",
    ],
    estValueLow: 5000,
    estValueHigh: 12000,
    buyingWindowEstimate: "Check scope overlap",
    gcName: "Metro Interiors",
    architectName: "Studio Form",
    ownerName: "53rd Retail LLC",
    hasSignPermit: true,
    lastActivityAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    filingDate: new Date(Date.now() - 55 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "nyc:2003344:B00333444-I1",
    city: "nyc",
    bin: "2003344",
    jobNumber: "B00333444-I1",
    address: "1200 Broadway",
    borough: "Manhattan",
    zip: "10001",
    latitude: 40.7472,
    longitude: -73.9881,
    jobType: "Alteration",
    buildingType: "Commercial",
    occupancy: "Office",
    description: "Office lobby and elevator modernization",
    estimatedJobCost: 2_800_000,
    phase: "interior_finishing",
    phaseConfidence: 0.8,
    score: 88,
    scoreReasons: [
      "Interior alteration / finishing permits active",
      "Permit activity in the last 14 days",
      "Substantial job cost ($2M+)",
      "Architect of record: Brightwell Architects",
    ],
    estValueLow: 12000,
    estValueHigh: 22000,
    buyingWindowEstimate: "2–4 weeks",
    gcName: null,
    architectName: "Brightwell Architects",
    ownerName: "Broadway Office Trust",
    hasSignPermit: false,
    lastActivityAt: new Date(Date.now() - 11 * 86400000).toISOString(),
    filingDate: new Date(Date.now() - 48 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_EVENTS: ProjectEvent[] = [
  {
    id: "evt-1",
    projectId: SEED_PROJECTS[0].id,
    type: "new_hot",
    title: "New hot opportunity",
    body: "350 5th Avenue scored 96 — Interior Finishing",
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: "evt-2",
    projectId: SEED_PROJECTS[1].id,
    type: "phase_change",
    title: "Moved into Sign-Ready",
    body: "200 West 57th Street — CO activity detected",
    createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
  },
  {
    id: "evt-3",
    projectId: SEED_PROJECTS[5].id,
    type: "score_jump",
    title: "Score jumped",
    body: "1200 Broadway: 72 → 88",
    createdAt: new Date(Date.now() - 26 * 3600000).toISOString(),
  },
  {
    id: "evt-4",
    projectId: SEED_PROJECTS[0].id,
    type: "gc_identified",
    title: "GC identified",
    body: "Apex Construction LLC linked to 350 5th Avenue",
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
];

/** Top NYC coverage for demo — replaced at sync time with live hot zips when available. */
export const DEMO_USER: UserRecord = {
  id: "user-demo",
  firebaseUid: "demo-uid",
  email: "demo@procurity.pro",
  name: "Demo Rep",
  plan: "pro",
  zipCodes: [],
  trialEndsAt: new Date(Date.now() + 7 * 86400000).toISOString(),
  stripeCustomerId: null,
  stripeSubscriptionId: null,
  zipAllowance: 25,
  notificationPrefs: {
    email: true,
    hotOpportunities: true,
    phaseChanges: true,
  },
  onboardingComplete: true,
  createdAt: new Date().toISOString(),
};
